<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <SatelliteResourceLanguages>zh-CN;en-US</SatelliteResourceLanguages>
        <InvariantGlobalization>false</InvariantGlobalization>
        <ApplicationIcon>icon.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <Resource Include="icon.ico"/>
        <Resource Include="ResImage\TH6\Rumia\1.png"/>
        <Resource Include="ResImage\TH6\Rumia\2.png"/>
        <Resource Include="ResImage\TH6\Rumia\3.png"/>
        <Resource Include="ResImage\TH6\Rumia\4.png"/>
        <Resource Include="ResImage\TH6\Rumia\5.png"/>
        <Resource Include="ResImage\TH6\Rumia\sup.png"/>
        <Resource Include="ResImage\TH6\Cirno\1.png"/>
        <Resource Include="ResImage\TH6\Cirno\2.png"/>
        <Resource Include="ResImage\TH6\Cirno\3.png"/>
        <Resource Include="ResImage\TH6\Cirno\4.png"/>
        <Resource Include="ResImage\TH6\Cirno\5.png"/>
        <Resource Include="ResImage\TH7\Youmu\1.png"/>
        <Resource Include="ResImage\TH7\Youmu\2.png"/>
        <Resource Include="ResImage\TH7\Youmu\3.png"/>
        <Resource Include="ResImage\TH7\Youmu\4.png"/>
        <Resource Include="ResImage\TH7\Youmu\5.png"/>
        <None Update="AIWeb\**\*">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
        <None Update="MusicPlayist\**\*">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
        <None Update="Text\**\*">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
        <None Update="WebGame\**\*">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>

  
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4258.31" />
        <PackageReference Include="ModernWpfUI" Version="0.9.6"/>
        <PackageReference Include="TagLibSharp2" Version="0.6.0" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Data\"/>
        <Folder Include="ExternalChars\"/>
        <Folder Include="ResImage\TH6\Rumia\"/>
        <Folder Include="Text\" />
        <Folder Include="Windows\"/>
    </ItemGroup>

    <ItemGroup>
        <Page Update="BubbleWindows.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="MainWindow.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
    </ItemGroup>

</Project>
