<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <SatelliteResourceLanguages>zh-CN;en-US</SatelliteResourceLanguages>
        <InvariantGlobalization>false</InvariantGlobalization>
    </PropertyGroup>

    <ItemGroup>
        <Resource Include="NewDirectory1\052_00.png" />
        <Resource Include="NewDirectory1\052_01.png" />
        <Resource Include="NewDirectory1\052_02.png" />
        <Resource Include="NewDirectory1\052_03.png" />
        <Resource Include="NewDirectory1\052_04.png" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="ModernWpfUI" Version="0.9.6" />
    </ItemGroup>

</Project>
